version: "3"

services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/nod_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 80:80

  backend:
    build: backend
    volumes:
      - ./backend:/app
