site_name: the14thset
site_description: Website for the convocation of Covenant University's 14th set.
repo_url: https://github.com/olaoluwa-98/fourteenth-set
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/olaoluwa-98">olaoluwa-98</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
