# Generated by Django 2.0.10 on 2019-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20190213_1032")]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="user_email",
            field=models.EmailField(db_index=True, max_length=50),
        )
    ]
