# Generated by Django 2.0.10 on 2019-02-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190213_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='user_email',
            field=models.EmailField(db_index=True, max_length=50, null=True),
        ),
    ]
